services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing_app:1.0.0
    container_name: ticketing_app
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17
    container_name: ticketing_postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
