spring:
  application:
    name: etick
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require&channel_binding=require
    #    username: ${POSTGRES_USERNAME}
    #    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/ticketing_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        batch_size: 30
        fetch_size: 30
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      cache:
        use_query_cache: true
        use_second_level_cache: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${APP_PORT:8080}